### ISSUE TITLE
Wrong definition of SaveAsCsv

### ISSUE THREAD

**Issue by lokijota** [Microsoft/MLADS2018-QuantumML#2]
It is:

`static void SaveAsCsv(double[] data, int[] labels)`

should be:

`static void SaveAsCsv(double[] data, long[] labels)`

Generates a compilation error when uncommenting the SaveAsCsv call.

**Comment by tcNickolas** [comment]
Indeed we switched to `long` labels and didn't update the signature.
Good catch, thank you for fixing it!
